/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.DBQuanLyVatTuNongNghiep;
import Model.NhanVien;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class DangNhap_GUI extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap_GUI() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
        this.setLocationRelativeTo(this);              
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new button.Button();
        jCheckBox1 = new javax.swing.JCheckBox();
        txt_TenDangNhap = new textfield.TextField();
        txt_matKhau = new textfield.PasswordField();
        btn_dangnhap = new button.Button();

        button1.setText("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("frame_dangnhap"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        jCheckBox1.setText("nhớ mật khẩu");

        txt_TenDangNhap.setLabelText("Tên đăng nhập");
        txt_TenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenDangNhapActionPerformed(evt);
            }
        });

        txt_matKhau.setLabelText("Mật khẩu");
        txt_matKhau.setShowAndHide(true);

        btn_dangnhap.setBackground(new java.awt.Color(45, 153, 174));
        btn_dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangnhap.setText("Đăng Nhập");
        btn_dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        btn_dangnhap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_dangnhapKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn_dangnhapKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_matKhau, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addComponent(txt_TenDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addComponent(btn_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(218, 218, 218))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txt_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGap(32, 32, 32)
                .addComponent(btn_dangnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP)
            btn_dangnhapActionPerformed(null);
    }//GEN-LAST:event_formKeyReleased

    private void txt_TenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenDangNhapActionPerformed

    private void btn_dangnhapKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_dangnhapKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangnhapKeyTyped

    private void btn_dangnhapKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_dangnhapKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_UP)
        btn_dangnhapActionPerformed(null);
    }//GEN-LAST:event_btn_dangnhapKeyReleased

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        // TODO add your handling code here:
        String tenDangNhap = txt_TenDangNhap.getText();
        if(tenDangNhap.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được để trống");
            txt_TenDangNhap.requestFocus();
            return;
        }
        String matKhau = txt_matKhau.getText();
        if(matKhau.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mặt khẩu");
            txt_matKhau.requestFocus();
            return;
        }
        DBQuanLyVatTuNongNghiep db = new DBQuanLyVatTuNongNghiep();
        NhanVien user = db.getNhanViens().get(nv->nv.getTenDangNhap().equalsIgnoreCase(tenDangNhap));
        if(user == null)
        {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không tồn tại !!!");
            txt_TenDangNhap.setText("");
            txt_matKhau.setText("");
            txt_TenDangNhap.requestFocus();
            return;
        }
        if(user.getMatKhau().equals(matKhau))
        {
            new Main(db,user).setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhap_GUI().setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button btn_dangnhap;
    private button.Button button1;
    private javax.swing.JCheckBox jCheckBox1;
    private textfield.TextField txt_TenDangNhap;
    private textfield.PasswordField txt_matKhau;
    // End of variables declaration//GEN-END:variables
}
