/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.ChiTietDatHang;
import Model.ChiTietHoaDon;
import Model.ChiTietLoaiHang;
import Model.ColorCustom;
import Model.DBQuanLyVatTuNongNghiep;
import Model.HoaDon;
import Model.NguonHang;
import Model.NhaCungCap;
import Model.NhanVien;
import Model.PhieuDatHang;
import java.net.HttpURLConnection;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javaswingdev.Notification;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import table.TableCustom;
import textfield.TextFieldAnimation;

/**
 *
 * @author Admin
 */
public class DatHang_GUI extends javax.swing.JPanel {

    /**
     * Creates new form DatHang_GUI
     */
    DefaultTableModel dtm =null;
    DBQuanLyVatTuNongNghiep db;
     TextFieldAnimation txt_timKiem = null;
    NhanVien user;
    int idxSua = -1;
    String maNCCSelect = null;
    public DatHang_GUI(DBQuanLyVatTuNongNghiep db, NhanVien user, TextFieldAnimation txt_timKiem) {
        initComponents();
        this.db = db;
        this.user = user;
        this.txt_timKiem = txt_timKiem;
        db.getNhaCungCaps().forEach(n->cbo_ncc.addItem(n.getMaNCC()+" - "+n.getTenNCC()));
        Vector header = new Vector();
        header.add("Mã");
        header.add("Tên sản phẩm");
        header.add("Loại");
        header.add("Đơn giá");
        header.add("Số lượng");
        header.add("Tổng tiền");
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(header);
        tbl_datHang.setModel(dtm);
        btn_xoa.setBackground(btn_xoa.getBackground());
        txt_giaNhap.setEditable(false);
        btn_huy.setEnabled(false);
        btn_xoa.setEnabled(false);  
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboSuggestionUI1 = new combo_suggestion.ComboSuggestionUI();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_soLuong = new javax.swing.JTextField();
        btn_cong = new javax.swing.JButton();
        btn_tru = new javax.swing.JButton();
        cbo_hangHoa = new combo_suggestion.ComboBoxSuggestion();
        btn_soSanhGia = new button.Button();
        txt_giaNhap = new textfield_2.TextField();
        btn_capNhat = new button.Button();
        btn_xoa = new button.Button();
        btn_huy = new button.Button();
        btn_lamMoi = new button.Button();
        jLabel4 = new javax.swing.JLabel();
        cbo_ncc = new combo_suggestion.ComboBoxSuggestion();
        jLabel1 = new javax.swing.JLabel();
        btn_datHang = new button.Button();
        tableScrollButton1 = new table.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datHang = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        setRequestFocusEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Chọn hàng hóa");

        txt_soLuong.setText("1");
        txt_soLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongActionPerformed(evt);
            }
        });
        txt_soLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_soLuongKeyTyped(evt);
            }
        });

        btn_cong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_cong.setText("+");
        btn_cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_congActionPerformed(evt);
            }
        });

        btn_tru.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_tru.setText("-");
        btn_tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_truActionPerformed(evt);
            }
        });

        cbo_hangHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_hangHoaActionPerformed(evt);
            }
        });

        btn_soSanhGia.setBackground(new java.awt.Color(45, 153, 174));
        btn_soSanhGia.setForeground(new java.awt.Color(255, 255, 255));
        btn_soSanhGia.setText("So Sánh giá");
        btn_soSanhGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_soSanhGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_soSanhGiaActionPerformed(evt);
            }
        });

        btn_capNhat.setBackground(new java.awt.Color(12, 87, 118));
        btn_capNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_capNhat.setText("Thêm");
        btn_capNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(45, 153, 174));
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_lamMoi.setBackground(new java.awt.Color(248, 218, 208));
        btn_lamMoi.setForeground(new java.awt.Color(0, 0, 0));
        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Giá nhập");

        cbo_ncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_nccActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Chọn nhà cung cấp:");

        btn_datHang.setBackground(new java.awt.Color(0, 28, 68));
        btn_datHang.setForeground(new java.awt.Color(255, 255, 255));
        btn_datHang.setText("Đặt hàng");
        btn_datHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_datHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 826, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(cbo_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(100, 100, 100))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(150, 150, 150)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_cong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_tru))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(cbo_hangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_capNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(80, 80, 80)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_datHang, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_soSanhGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(4, 4, 4)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbo_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbo_hangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_capNhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)))
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3))
                    .addComponent(btn_soSanhGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btn_datHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_giaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_cong)
                                    .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_tru))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_lamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );

        tbl_datHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_datHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_datHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_datHang);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 162, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private String getMaNCCSelect()
    {
        return Arrays.asList(cbo_ncc.getSelectedItem().toString().split(" - ")).get(0);
    }
    
    private void loadDuLieuNguonHang()
    {
        NhaCungCap ncc = db.getNhaCungCaps().get(n->n.getMaNCC().equals(maNCCSelect));
            cbo_hangHoa.removeAllItems();
            if(ncc!=null)
                ncc.getNguonHangs().forEach(nh->cbo_hangHoa.addItem(nh.getMaCTLH()+" - "+nh.getChiTietLoaiHang().getTenLoai()+" - "+nh.getChiTietLoaiHang().getHangHoa().getTenHang()));
    }
    
    private void tbl_datHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_datHangMouseClicked
        // TODO add your handling code here:
        idxSua = tbl_datHang.getSelectedRow();        
        btn_capNhat.setText("Cập nhật");
        btn_huy.setEnabled(true);
        btn_xoa.setEnabled(true);
        btn_xoa.setBackground(ColorCustom.XANH_NHAT);
        btn_huy.setBackground(ColorCustom.TRANG);
        Vector v = (Vector)dtm.getDataVector().get(idxSua);
        NguonHang nh = db.getNguonHangs().get(n->n.getMaNCC().equals(getMaNCCSelect())&&n.getMaCTLH().equals(v.get(0).toString()));
        txt_giaNhap.setText(String.valueOf(nh.getGiaNhap()));
        for(int i = 0 ; i< cbo_hangHoa.getItemCount();i++)        
            if(cbo_hangHoa.getItemAt(i).toString().contains(nh.getMaCTLH()))
            {
                cbo_hangHoa.setSelectedIndex(i);                
                break;
            }   
    }//GEN-LAST:event_tbl_datHangMouseClicked

    private NguonHang getNguonHangSelect()
    {
        String maCTLH = getMaCTLHSelect();
        return db.getNguonHangs().get(nh->nh.getMaNCC().equals(maNCCSelect) && nh.getMaCTLH().equals(maCTLH));
    }
    
    private void txt_soLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soLuongKeyTyped
        // TODO add your handling code here:
        String strsl = txt_soLuong.getText();
        if(strsl.length()==9)
        {
            evt.consume();
            return;
        }
        if(strsl.isEmpty() && evt.getKeyChar()=='0')        
            evt.consume();        
        else if(evt.getKeyChar()<'0' || evt.getKeyChar() > '9')
            evt.consume();        
    }//GEN-LAST:event_txt_soLuongKeyTyped

    private void btn_congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_congActionPerformed
        // TODO add your handling code here:
        String strsl = txt_soLuong.getText();
        if(strsl.isEmpty())
            txt_soLuong.setText("1");
        else
        {            
            int sl = Integer.parseInt(strsl);        
            txt_soLuong.setText(String.valueOf(++sl));
        }
    }//GEN-LAST:event_btn_congActionPerformed

    private void btn_truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_truActionPerformed
        // TODO add your handling code here:
        String strsl = txt_soLuong.getText();
        if(strsl.equals("1"))
            return;
        int sl = Integer.parseInt(strsl);
        txt_soLuong.setText(String.valueOf(--sl));
    }//GEN-LAST:event_btn_truActionPerformed

    private void txt_soLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongActionPerformed

    private void cbo_nccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_nccActionPerformed
        // TODO add your handling code here:
        if(cbo_ncc.getSelectedIndex()<0)
            return;
        String maNCCSelect_tam = getMaNCCSelect();
        if(maNCCSelect_tam.equals(maNCCSelect))
            return;
        try
        {
            if(dtm.getRowCount() == 0 ||(dtm.getRowCount() > 0 && JOptionPane.showConfirmDialog(this, "Nếu chọn nhà cung cấp mới, việc lập các dòng đặt hàng trước đó sẽ bị xóa!!!\nXác nhận tiếp tục?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION))
            {
                dtm.setRowCount(0);
                maNCCSelect = maNCCSelect_tam;     
                loadDuLieuNguonHang();
            }
        }catch(Exception e){
            maNCCSelect = maNCCSelect_tam;     
            loadDuLieuNguonHang();
        }
    }//GEN-LAST:event_cbo_nccActionPerformed

    private void cbo_hangHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_hangHoaActionPerformed
        // TODO add your handling code here:
           try
        {
        if(cbo_hangHoa.getSelectedIndex()==-1)
            return;        
            NguonHang nh = getNguonHangSelect();
            if(nh!=null)
                txt_giaNhap.setText(String.valueOf(nh.getGiaNhap()));
        }
        catch(Exception e){}
    }//GEN-LAST:event_cbo_hangHoaActionPerformed

    private void btn_soSanhGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_soSanhGiaActionPerformed
        // TODO add your handling code here:
        ChiTietLoaiHang ctlh = db.getChiTietLoaiHangs().get(ct->ct.getMaCTLH().equals(getMaCTLHSelect()));
        SoSanhGia ssg = new SoSanhGia(db,ctlh);
        ssg.pack();
        ssg.setLocationRelativeTo(null);
        ssg.setVisible(true);
        ssg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);    
    }//GEN-LAST:event_btn_soSanhGiaActionPerformed

    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
        String strSL = txt_soLuong.getText();
        if(strSL.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Số lượng mua không được để trống!!!");            
            return;
        }        
        int sl = Integer.parseInt(strSL);  
        NguonHang nh = getNguonHangSelect();
        int i = 0;
        int gia = nh.getGiaNhap();
        for(Object item : dtm.getDataVector())
        {
            Vector v = (Vector)item;
            if(v.get(0).toString() == nh.getMaCTLH())
            {              
                sl = idxSua == -1 ? (int) v.get(4)+sl:sl;                
                v.set(4,sl);                
                v.set(3, gia); 
                v.set(5,gia*sl);
                //trường hợp sửa
                if(idxSua != -1 && idxSua != i)
                {
                    dtm.removeRow(idxSua);                    
                }
                tbl_datHang.updateUI();
                btn_huyActionPerformed(null);
                return;
            }
            i ++;
        }                  
            Vector ctdh = new Vector();
            ctdh.add(nh.getMaCTLH());
            ctdh.add(nh.getChiTietLoaiHang().getHangHoa().getTenHang());
            ctdh.add(nh.getChiTietLoaiHang().getTenLoai());
            ctdh.add(gia);
            ctdh.add(sl);
            ctdh.add(gia*sl); 
            if(idxSua==-1)
                dtm.addRow(ctdh);                
            else
            {                
                dtm.removeRow(idxSua);
                dtm.insertRow(idxSua, ctdh);
                tbl_datHang.updateUI();
                btn_huyActionPerformed(null);
            }
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        dtm.removeRow(idxSua);
        btn_huyActionPerformed(null);
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        btn_capNhat.setText("Thêm");
        btn_xoa.setEnabled(false);
        btn_huy.setEnabled(false);
        idxSua = -1;
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
         dtm.setRowCount(0);
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void btn_datHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datHangActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        if(dtm.getRowCount()==0)
        {
            Notification panel = new Notification(frame, Notification.Type.INFO, Notification.Location.TOP_RIGHT, "Cần phải có ít nhất 1 chi tiết đơn đặt hàng!!!");
            panel.showNotification();
            //JOptionPane.showMessageDialog(this, "Cần phải có ít nhất 1 chi tiết đơn đặt hàng!!!"); 
            return ;
            
        }
        if(JOptionPane.showConfirmDialog(this, "Xác nhận đặt hàng?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            String soDonDatHang = null;
            int sl = 1;
            do
            {
                int slHD = db.getPhieuDatHangs().size()+1;
                String soddh = soDonDatHang = "DDH00"+String.valueOf(slHD+sl++);    
                if(db.getPhieuDatHangs().get(t->t.getSoDonDatHang().contains(soddh)) == null)
                {
                    soDonDatHang = soddh;
                    break;
                }
            } while(true);  
            int tongSl = 0;
            PhieuDatHang pdhMoi = new PhieuDatHang(soDonDatHang,maNCCSelect, user.getMaNV());
            int tongTien = 0;
            ArrayList<ChiTietDatHang> ctdhs = new ArrayList<ChiTietDatHang>();
            for (Object item : dtm.getDataVector()) {
                Vector v = (Vector) item;
                ChiTietDatHang ctdh = new ChiTietDatHang(soDonDatHang, (String) v.get(0), (int) v.get(3), (int) v.get(4));
                tongSl+=(int) v.get(4);
                tongTien += (int)v.get(5);
                ctdhs.add(ctdh);
            }
            pdhMoi.setTongSL(tongSl);        
            pdhMoi.setThanhTien(tongTien);            
            if(db.getPhieuDatHangs().insert(pdhMoi))
            {
                int thanhcong = db.getChiTietDatHangs().insert(ctdhs);
                if(thanhcong == ctdhs.size())     
                {
                    Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Bạn đã đặt hàng thành công");
                    panel.showNotification();
                    //JOptionPane.showMessageDialog(this, "Bạn đã đặt hàng thành công");
                }                                                        
                else                
                {
                    Notification panel = new Notification(frame, Notification.Type.INFO, Notification.Location.TOP_RIGHT, thanhcong + " chi tiết đặt hàng đầu tiên được tạo!!!");
                    panel.showNotification();
                    //JOptionPane.showMessageDialog(this, thanhcong + " chi tiết đặt hàng đầu tiên được tạo!!!");
                }                                    
                dtm.setRowCount(0);
                return;
            }
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Thao tác thất bại");
                    panel.showNotification();
            //JOptionPane.showMessageDialog(this, "Thao tác thất bại");            
        }
        
    }//GEN-LAST:event_btn_datHangActionPerformed

    
    private String getMaCTLHSelect()
    {
        return Arrays.asList(cbo_hangHoa.getSelectedItem().toString().split(" - ")).get(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button btn_capNhat;
    private javax.swing.JButton btn_cong;
    private button.Button btn_datHang;
    private button.Button btn_huy;
    private button.Button btn_lamMoi;
    private button.Button btn_soSanhGia;
    private javax.swing.JButton btn_tru;
    private button.Button btn_xoa;
    private combo_suggestion.ComboBoxSuggestion cbo_hangHoa;
    private combo_suggestion.ComboBoxSuggestion cbo_ncc;
    private combo_suggestion.ComboSuggestionUI comboSuggestionUI1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private table.TableScrollButton tableScrollButton1;
    private javax.swing.JTable tbl_datHang;
    private textfield_2.TextField txt_giaNhap;
    private javax.swing.JTextField txt_soLuong;
    // End of variables declaration//GEN-END:variables
}
