/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.ChiTietLoaiHang;
import Model.ColorCustom;
import Model.DBQuanLyVatTuNongNghiep;
import Model.GiaMatHang;
import Model.HangHoa;
import Model.LoaiHang;
import Model.NhanVien;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.FileNameMap;
import java.net.URLConnection;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingdev.Notification;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import table.TableCustom;

/**
 *
 * @author Admin
 */
public class QuanLyHangHoa_GUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyHangHoa_GUI
     */
    DBQuanLyVatTuNongNghiep db = null;
    NhanVien user = null;
    DefaultTableModel dtm_hanghoa =null;
    DefaultTableModel dtm_hhLoai =null;
    DefaultTableModel dtm_hhGMH =null;
    Vector headerHH = null;
    Vector headerLHH = null;
    Vector headerGMH = null;
    int idxSua = -1;
    int idxSuaCTLH = -1;
    int idxSuaGMH = -1;
    public QuanLyHangHoa_GUI(DBQuanLyVatTuNongNghiep db, NhanVien user) {
        initComponents();
        this.db = db;
        this.user = user;
        
        dtm_hanghoa = new DefaultTableModel();        
        tbl_hangHoa.setModel(dtm_hanghoa);        
        headerHH = new Vector();        
        headerHH.add("Mã hàng");
        headerHH.add("Tên hàng");
        headerHH.add("Mã loại hàng");
        headerHH.add("Đơn vị loại");        
        chk_tatca.setSelected(true);
        db.getLoaiHangs().forEach(t->cbo_loaiHang.addItem(t.getMaLoaiHang().trim()+" - "+t.getTenLoaiHang()));              
        txt_maHangHoa.setEditable(false);
        btn_xoa.setEnabled(false);                
        txt_anh.setVisible(false);
        txt_path.setVisible(false);
        btn_huy.setEnabled(false); 
                  
        headerLHH = new Vector();
        headerLHH.add("Mã chi tiết");
        headerLHH.add("Tên loại");
        headerLHH.add("Giá mặc định");
        headerLHH.add("Số lượng tồn");
        dtm_hhLoai = new DefaultTableModel();
        tbl_CTLH.setModel(dtm_hhLoai);
        dtm_hhLoai.setColumnIdentifiers(headerLHH);
        txt_maCTLH.setEditable(false);
        btn_xoaCTLH.setEnabled(false);
        btn_huyCTLH.setEnabled(false);
        btn_capnhatCTLH.setEnabled(false);
        
        dtm_hhGMH = new DefaultTableModel();
        tbl_giaMatHang.setModel(dtm_hhGMH);
        headerGMH = new Vector();        
        headerGMH.add("Mã chi tiết");
        headerGMH.add("Giá bán");
        headerGMH.add("Số lượng yêu cầu");        
        btn_xoaGiaMH.setEnabled(false);
        btn_huyGiaMH.setEnabled(false);
        btn_capNhatGiaMH.setEnabled(false);
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        TableCustom.apply(jScrollPane2, TableCustom.TableType.MULTI_LINE);
        TableCustom.apply(jScrollPane3, TableCustom.TableType.MULTI_LINE);
        loadData();        
    }   
     
    void loadData()
    {
        dtm_hanghoa.setDataVector(db.getHangHoas().getData("AnhHangHoa"), headerHH);
        cbo_loaiHang.setEnabled(false);
        String maHH = taoMaHangHoa();
        txt_maHangHoa.setText(maHH);
        loadDataCTLH();     
        loadDataGiaMatHang();
    }
    void loadDataCTLH()
    {
        dtm_hhLoai.setDataVector(db.getChiTietLoaiHangs().getData("MaHang"), headerLHH);
        String maCTLH = taoMaChiTietLoaiHang();
        txt_maCTLH.setText(maCTLH);
    }
    
    void loadDataGiaMatHang()
    {
        dtm_hhGMH.setDataVector(db.getGiaMatHangs().getData(),headerGMH);
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_anhHangHoa = new javax.swing.JLabel();
        txt_anh = new javax.swing.JTextField();
        txt_path = new javax.swing.JTextField();
        btn_capnhat = new button.Button();
        btn_xoa = new button.Button();
        btn_huy = new button.Button();
        cbo_loaiHang = new combo_suggestion.ComboBoxSuggestion();
        txt_maHangHoa = new textfield.TextField();
        txt_tenHangHoa = new textfield.TextField();
        txt_donViTinh = new textfield.TextField();
        btn_chonFileAnh = new button.Button();
        chk_tatca = new checkbox.JCheckBoxCustom();
        tableScrollButton1 = new table.TableScrollButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_hangHoa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_capnhatCTLH = new button.Button();
        btn_xoaCTLH = new button.Button();
        btn_huyCTLH = new button.Button();
        txt_maCTLH = new textfield.TextField();
        txt_giaMacDinh = new textfield.TextField();
        txt_soLuongTon = new textfield.TextField();
        txt_tenloai = new textfield.TextField();
        tableScrollButton2 = new table.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_CTLH = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        btn_capNhatGiaMH = new button.Button();
        btn_xoaGiaMH = new button.Button();
        btn_huyGiaMH = new button.Button();
        txt_dieukien = new textfield.TextField();
        txt_giaBan = new textfield.TextField();
        tableScrollButton3 = new table.TableScrollButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_giaMatHang = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Danh mục hàng hóa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        label_anhHangHoa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_anhHangHoa.setText("Ảnh hàng hóa");
        label_anhHangHoa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn_capnhat.setBackground(new java.awt.Color(12, 87, 118));
        btn_capnhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_capnhat.setText("Thêm");
        btn_capnhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatActionPerformed(evt);
            }
        });

        btn_xoa.setBackground(new java.awt.Color(45, 153, 174));
        btn_xoa.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoa.setText("Xóa");
        btn_xoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        cbo_loaiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_loaiHangActionPerformed(evt);
            }
        });

        txt_maHangHoa.setLabelText("Mã hàng hóa");

        txt_tenHangHoa.setLabelText("Tên hàng hóa");
        txt_tenHangHoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tenHangHoaKeyReleased(evt);
            }
        });

        txt_donViTinh.setLabelText("Đơn vị loại");
        txt_donViTinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_donViTinhKeyReleased(evt);
            }
        });

        btn_chonFileAnh.setBackground(new java.awt.Color(248, 218, 208));
        btn_chonFileAnh.setForeground(new java.awt.Color(0, 0, 0));
        btn_chonFileAnh.setText("Chọn ảnh");
        btn_chonFileAnh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_chonFileAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chonFileAnhActionPerformed(evt);
            }
        });

        chk_tatca.setBackground(new java.awt.Color(0, 153, 153));
        chk_tatca.setText("Tất cả");
        chk_tatca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_tatcaActionPerformed(evt);
            }
        });

        tbl_hangHoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_hangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_hangHoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_hangHoa);

        tableScrollButton1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(chk_tatca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbo_loaiHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txt_maHangHoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_tenHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txt_donViTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE))))
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 87, Short.MAX_VALUE)
                                .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)))
                        .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(label_anhHangHoa, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                            .addComponent(btn_chonFileAnh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_anhHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(btn_chonFileAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbo_loaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_tatca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txt_maHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_tenHangHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_donViTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_huy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_anh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setForeground(new java.awt.Color(0, 204, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("QUẢN LÝ HÀNG HÓA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Danh mục loại hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        btn_capnhatCTLH.setBackground(new java.awt.Color(12, 87, 118));
        btn_capnhatCTLH.setForeground(new java.awt.Color(255, 255, 255));
        btn_capnhatCTLH.setText("Thêm");
        btn_capnhatCTLH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capnhatCTLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capnhatCTLHActionPerformed(evt);
            }
        });

        btn_xoaCTLH.setBackground(new java.awt.Color(45, 153, 174));
        btn_xoaCTLH.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaCTLH.setText("Xóa");
        btn_xoaCTLH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaCTLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaCTLHActionPerformed(evt);
            }
        });

        btn_huyCTLH.setText("Hủy");
        btn_huyCTLH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_huyCTLH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyCTLHActionPerformed(evt);
            }
        });

        txt_maCTLH.setLabelText("Mã chi tiết loại hàng");
        txt_maCTLH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_maCTLHKeyReleased(evt);
            }
        });

        txt_giaMacDinh.setLabelText("Giá mặt định");
        txt_giaMacDinh.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_giaMacDinhKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_giaMacDinhKeyTyped(evt);
            }
        });

        txt_soLuongTon.setLabelText("Số lượng tồn");
        txt_soLuongTon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_soLuongTonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_soLuongTonKeyTyped(evt);
            }
        });

        txt_tenloai.setLabelText("Tên loại");
        txt_tenloai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_tenloaiKeyReleased(evt);
            }
        });

        tbl_CTLH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_CTLH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_CTLHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_CTLH);

        tableScrollButton2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tableScrollButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txt_maCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txt_tenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(txt_giaMacDinh, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(txt_soLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_capnhatCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xoaCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_huyCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(86, 86, 86))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_maCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_tenloai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_giaMacDinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_soLuongTon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capnhatCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huyCTLH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), "Danh mục giá theo số lượng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 153, 255))); // NOI18N

        btn_capNhatGiaMH.setBackground(new java.awt.Color(12, 87, 118));
        btn_capNhatGiaMH.setForeground(new java.awt.Color(255, 255, 255));
        btn_capNhatGiaMH.setText("Thêm");
        btn_capNhatGiaMH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_capNhatGiaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatGiaMHActionPerformed(evt);
            }
        });

        btn_xoaGiaMH.setBackground(new java.awt.Color(45, 153, 174));
        btn_xoaGiaMH.setForeground(new java.awt.Color(255, 255, 255));
        btn_xoaGiaMH.setText("Xóa");
        btn_xoaGiaMH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xoaGiaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaGiaMHActionPerformed(evt);
            }
        });

        btn_huyGiaMH.setText("Hủy");
        btn_huyGiaMH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_huyGiaMH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyGiaMHActionPerformed(evt);
            }
        });

        txt_dieukien.setLabelText("Số lượng yêu cầu");
        txt_dieukien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_dieukienKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dieukienKeyTyped(evt);
            }
        });

        txt_giaBan.setLabelText("Giá bán");
        txt_giaBan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_giaBanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_giaBanKeyTyped(evt);
            }
        });

        tbl_giaMatHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_giaMatHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_giaMatHangMouseClicked(evt);
            }
        });
        tbl_giaMatHang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_giaMatHangKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_giaMatHang);

        tableScrollButton3.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScrollButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_giaBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_dieukien, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btn_capNhatGiaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_xoaGiaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_huyGiaMH, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_dieukien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txt_giaBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_capNhatGiaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoaGiaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_huyGiaMH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableScrollButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    String getMaLoai()
    {
        return Arrays.asList(cbo_loaiHang.getSelectedItem().toString().split("-")).get(0).trim();
    }
    ImageIcon ResizeImage(String path)
    {
        ImageIcon myImg = new ImageIcon(path);
        Image img = myImg.getImage();
        Image newImg = img.getScaledInstance(label_anhHangHoa.getWidth(), label_anhHangHoa.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image;
    }
    private void tbl_hangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_hangHoaMouseClicked
        // TODO add your handling code here:        
        int idxSua_tam = tbl_hangHoa.getSelectedRow();
        if(idxSua_tam==idxSua)
            return;
        idxSua = idxSua_tam;
        String maHangHoa = tbl_hangHoa.getValueAt(idxSua, 0).toString();
        HangHoa hh = db.getHangHoas().get(t->t.getMaHang().equals(maHangHoa));
        String ten = tbl_hangHoa.getValueAt(idxSua, 1).toString();
        String dvLoai = tbl_hangHoa.getValueAt(idxSua, 2).toString();        
        txt_maHangHoa.setText(maHangHoa);
        txt_tenHangHoa.setText(ten);
        txt_donViTinh.setText(dvLoai);  
        txt_anh.setText(hh.getAnhHangHoa());
        label_anhHangHoa.setText("");        
        label_anhHangHoa.setIcon(ResizeImage("src\\AnhHangHoa\\"+hh.getAnhHangHoa()));
        dtm_hhLoai.setDataVector(hh.getChiTietLoaiHangs().getData("MaHang"), headerLHH);
        btn_capnhat.setText("Cập nhật");
        cbo_loaiHang.setEnabled(false);
        btn_xoa.setEnabled(true);
        btn_huy.setEnabled(true);        
        btn_capnhatCTLH.setEnabled(true);
        
        btn_capnhatCTLH.setBackground(ColorCustom.XANH_DAM);
        btn_xoa.setBackground(ColorCustom.XANH_NHAT);
        btn_huy.setBackground(ColorCustom.TRANG);
        idxSuaCTLH = -1;
        loadGiaMatHangThuocHangHoa();
    }//GEN-LAST:event_tbl_hangHoaMouseClicked

    
    
    void checkInputHangHoa()
    {
        if(txt_tenHangHoa.getText().trim().isEmpty()&&txt_donViTinh.getText().trim().isEmpty())
            btn_huy.setEnabled(false);
        else
            btn_huy.setEnabled(true);
    }
    private void tbl_CTLHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_CTLHMouseClicked
        // TODO add your handling code here:
        int idxSuaCTLH_tam = tbl_CTLH.getSelectedRow();
        idxSuaCTLH = idxSuaCTLH_tam;
        String maCTLH = dtm_hhLoai.getValueAt(idxSuaCTLH, 0).toString();
        String tenLoai = dtm_hhLoai.getValueAt(idxSuaCTLH, 1).toString();
        ChiTietLoaiHang ctlh = db.getChiTietLoaiHangs().get(t->t.getMaCTLH().equalsIgnoreCase(maCTLH)&&t.getTenLoai().equalsIgnoreCase(tenLoai));
        dtm_hhGMH.setDataVector(ctlh.getGiaMatHangs().getData(), headerGMH);
        String maHH = ctlh.getMaHang();
        txt_maCTLH.setText(maCTLH);
        txt_tenloai.setText(tenLoai);
        txt_giaMacDinh.setText(dtm_hhLoai.getValueAt(idxSuaCTLH, 2).toString());
        txt_soLuongTon.setText(dtm_hhLoai.getValueAt(idxSuaCTLH, 3).toString());
        btn_capnhatCTLH.setText("Cập nhật");
        btn_xoaCTLH.setEnabled(true);
        btn_huyCTLH.setEnabled(true);
                
        btn_capNhatGiaMH.setEnabled(true);
        
        btn_capNhatGiaMH.setBackground(ColorCustom.XANH_DAM);
        btn_xoaCTLH.setBackground(ColorCustom.XANH_NHAT);
        btn_huyCTLH.setBackground(ColorCustom.TRANG);
       if(!maHH.equals(txt_maHangHoa.getText()))
        {            
            Vector data = dtm_hanghoa.getDataVector();        
            for (int i = 0 ;i< data.size();i++) {
                Vector v = (Vector)data.get(i);
                if(v.get(0).toString().equals(maHH))
                {                
                    tbl_hangHoa.setRowSelectionInterval(i,i);
                    tbl_hangHoaMouseClicked(null);
                    Vector vv = dtm_hhLoai.getDataVector();
                    for(int j =0;j<vv.size();j++)
                    {
                        Vector item = (Vector) vv.get(j);
                        if(item.get(0).toString().equals(maCTLH))
                        {                            
                            idxSuaCTLH = j;                 
                            return;
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_tbl_CTLHMouseClicked

    
    private void tbl_giaMatHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_giaMatHangMouseClicked
        // TODO add your handling code here:
        idxSuaGMH = tbl_giaMatHang.getSelectedRow();
        String maCTLH = dtm_hhGMH.getValueAt(idxSuaGMH, 0).toString();
        txt_giaBan.setText(dtm_hhGMH.getValueAt(idxSuaGMH, 1).toString());
        txt_dieukien.setText(dtm_hhGMH.getValueAt(idxSuaGMH, 2).toString());
        btn_xoaGiaMH.setEnabled(true);
        btn_huyGiaMH.setEnabled(true);
                 
        btn_xoaGiaMH.setBackground(ColorCustom.XANH_NHAT);
        btn_huyGiaMH.setBackground(ColorCustom.TRANG);
        btn_capNhatGiaMH.setText("Cập nhật");
        if(!maCTLH.equals(txt_maCTLH.getText()))
        {
            Vector v = dtm_hhLoai.getDataVector();
            for(int i = 0;i<v.size();i++)
            {
                Vector vv = (Vector) v.get(i);
                if(vv.get(0).toString().equals(maCTLH))
                {
                    tbl_CTLH.setRowSelectionInterval(i,i);
                    tbl_CTLHMouseClicked(null);
                    Vector v2 = dtm_hhGMH.getDataVector();
                    for(int j =0;j<v2.size();j++)
                    {
                        Vector item = (Vector) v2.get(j);
                        if(item.get(0).toString().equals(maCTLH) && item.get(2).toString().equals(txt_dieukien.getText()))
                        {                            
                            idxSuaGMH = j;  
                            return;
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_tbl_giaMatHangMouseClicked
    
    void checkInputGiaMatHang()
    {
        if(txt_giaBan.getText().trim().isEmpty()&&txt_dieukien.getText().trim().isEmpty())
            btn_huyGiaMH.setEnabled(false);
        else
            btn_huyGiaMH.setEnabled(true);
    }
    private void tbl_giaMatHangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_giaMatHangKeyReleased
        // TODO add your handling code here:        
    }//GEN-LAST:event_tbl_giaMatHangKeyReleased

    void checkInputCTLH()
    {
        if(txt_tenloai.getText().trim().isEmpty()&&txt_giaMacDinh.getText().trim().isEmpty()&&txt_soLuongTon.getText().trim().isEmpty())
            btn_huyCTLH.setEnabled(false);
        else
            btn_huyCTLH.setEnabled(true);
    }
    private void btn_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
         String maHH = txt_maHangHoa.getText().trim();
        String tenHH = txt_tenHangHoa.getText().trim();
        String dvTinh = txt_donViTinh.getText().trim(); 
        System.out.println(idxSua);
        if(tenHH.isEmpty())
        {
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Tên hàng hóa không được để trống!!!");
            panel.showNotification();
            //JOptionPane.showMessageDialog(this, "Tên hàng hóa không được để trống!!!");            
            txt_tenHangHoa.requestFocus();
            return;
        }
        else            
            if(idxSua ==-1 && db.getHangHoas().get(t->t.getTenHang().trim().equalsIgnoreCase(tenHH))!=null)
            {
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Tên hàng hóa này đã tồn tại!!!");
            panel.showNotification();
                //JOptionPane.showMessageDialog(this, "Tên hàng hóa này đã tồn tại!!!");
                txt_tenHangHoa.setText("");
                txt_tenHangHoa.requestFocus();
                return;
            }
        if(dvTinh.isEmpty())
        {
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Đơn vị không được bỏ trống");
            panel.showNotification();
            //JOptionPane.showMessageDialog(this, "Đơn vị không được bỏ trống");            
            txt_donViTinh.requestFocus();
            return;
        }
        if(JOptionPane.showConfirmDialog(this, "Xác nhận cập nhật dữ liệu","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {        
            String tenAnh = txt_anh.getText();
            String maLoai = getMaLoai();
            String path = txt_path.getText();
            boolean chk;
            HangHoa hh;
            if(idxSua == -1)
            {
                hh = new HangHoa(maHH, tenHH, tenAnh, maLoai, dvTinh);
                chk =  db.getHangHoas().insert(hh);            
            }
            else
            {
                hh = db.getHangHoas().get(t->t.getMaHang().trim().equalsIgnoreCase(maHH));
                hh.setAnhHangHoa(tenAnh);
                hh.setDonViTinh(dvTinh);
                hh.setTenHang(tenHH);
                chk = db.getHangHoas().update(hh);
            }                         
            if(chk)            
            {                                         
                if(!"".equals(txt_path.getText()))
                {
                    try {
                        File f = new File("src\\AnhHangHoa\\"+txt_anh.getText());                    
                        BufferedImage img = ImageIO.read(new File(txt_path.getText()));
                        String[] a = txt_anh.getText().split("\\Q.\\E");
                        String duoiAnh = Arrays.asList(a).get(a.length-1);
                        ImageIO.write(img, duoiAnh, f);
                    } catch (IOException ex) {
                        Logger.getLogger(QuanLyHangHoa_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
                Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Thao tác thành công");
            panel.showNotification();
            
                //JOptionPane.showMessageDialog(this, "Thao tác thành công");   
                if(idxSua==-1)
                    dtm_hanghoa.addRow(hh.getParameter("AnhHangHoa"));
                else
                {
                    dtm_hanghoa.removeRow(idxSua);
                    dtm_hanghoa.insertRow(idxSua, hh.getParameter("AnhHangHoa"));                    
                }                
                resetText();
            }
            else
                //JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi, vui lòng thử lại!");
            {
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Đã xảy ra lỗi, vui lòng thử lại!");
            panel.showNotification();
            return;
            }
        }
    }//GEN-LAST:event_btn_capnhatActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        String tenHH = dtm_hanghoa.getValueAt(idxSua, 1).toString();
        if(JOptionPane.showConfirmDialog(this, "Xác nhận xóa hàng hóa '"+tenHH+"'?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {      
            String maHH = txt_maHangHoa.getText().trim();
            HangHoa hh = db.getHangHoas().get(t->t.getMaHang().trim().equalsIgnoreCase(maHH));
            if(db.getHangHoas().delete(hh))
            {                
                dtm_hanghoa.removeRow(tbl_hangHoa.getSelectedRow());
                resetText();
                //JOptionPane.showMessageDialog(this, "Xóa thành công!!!");
                Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Xóa thành công!!!");
            panel.showNotification();
            }
            else
                //JOptionPane.showMessageDialog(this, "Xóa không thành công!!!");
            {
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Xóa không thành công!!!");
            panel.showNotification();
            }
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
         if(JOptionPane.showConfirmDialog(this, "Xác nhận hoàn tác?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            resetText();                                    
            if(!chk_tatca.isSelected())      
            {
                cbo_loaiHang.setEnabled(true);            
                cbo_loaiHangActionPerformed(null);
            }
        }
    }//GEN-LAST:event_btn_huyActionPerformed

    private void cbo_loaiHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_loaiHangActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
         int row = cbo_loaiHang.getSelectedIndex();
        if(row<0)
            return;
        String maLoai = getMaLoai();     
        LoaiHang lh = db.getLoaiHangs().get(t->t.getMaLoaiHang().trim().equals(maLoai));
        if(lh.getHangHoas().size()==0)
        {
          //JOptionPane.showMessageDialog(this, "Không có mặt hàng nào thuộc loại hàng này!");
             Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Không có mặt hàng nào thuộc loại hàng này!");
            panel.showNotification();
          return;
        }        
        dtm_hanghoa.setDataVector(lh.getHangHoas().getData("AnhHangHoa"), headerHH);
        Vector dataCTLH = new Vector();
        Vector dataGMH = new Vector();
        lh.getHangHoas().forEach(t->{
            t.getChiTietLoaiHangs().forEach(v->{
                dataCTLH.add(v.getParameter());
                v.getGiaMatHangs().forEach(x->dataGMH.add(x.getParameter()));
            });
        });
        try
        {
            dtm_hhLoai.setDataVector(dataCTLH, headerLHH);
            dtm_hhGMH.setDataVector(dataGMH, headerGMH);
        }
        catch(Exception e){}
    }//GEN-LAST:event_cbo_loaiHangActionPerformed

    private void txt_tenHangHoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tenHangHoaKeyReleased
        // TODO add your handling code here:
        checkInputHangHoa();
    }//GEN-LAST:event_txt_tenHangHoaKeyReleased

    private void txt_donViTinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_donViTinhKeyReleased
        // TODO add your handling code here:
        checkInputHangHoa();
    }//GEN-LAST:event_txt_donViTinhKeyReleased

    private void btn_chonFileAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chonFileAnhActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        JFileChooser jFile = new JFileChooser();
        //jFile.setSize(1000, 1000);
        FileNameExtensionFilter fileExten = new FileNameExtensionFilter("Chọn hình ảnh","png","jpg");
        jFile.setFileFilter(fileExten);
        jFile.setMultiSelectionEnabled(false);
        
        if(jFile.showDialog(this, "Chọn hình ảnh")==JFileChooser.APPROVE_OPTION)
        {
            File f =  jFile.getSelectedFile();
            FileNameMap fileNameMap = URLConnection.getFileNameMap();            
            String mt = fileNameMap.getContentTypeFor(f.getName());
            if(mt == null)
            {
                //JOptionPane.showMessageDialog(this, "Định dạng file không hợp lệ!");
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Định dạng file không hợp lệ!");
            panel.showNotification();
                return;
            }
            label_anhHangHoa.setIcon(ResizeImage(f.getAbsolutePath()));
            txt_anh.setText(f.getName());   
            txt_path.setText(f.getAbsolutePath());
        }
    }//GEN-LAST:event_btn_chonFileAnhActionPerformed

    private void chk_tatcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_tatcaActionPerformed
        // TODO add your handling code here:
         resetText();                
        resetTextCTLH();
        if(chk_tatca.isSelected())   
        {            
            loadData();                               
        }
        else
        {
            cbo_loaiHang.setEnabled(true);
            cbo_loaiHangActionPerformed(null);
        }
    }//GEN-LAST:event_chk_tatcaActionPerformed

    private void btn_capnhatCTLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capnhatCTLHActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        String maHH = txt_maHangHoa.getText().trim();
        String maCTLH = txt_maCTLH.getText().trim();
        String tenLoai = txt_tenloai.getText().trim();    
        int giaMacDinh, soLuongTon;        
        if(tenLoai.isEmpty())
        {
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Tên phân loại hàng hóa không được để trống!!!");
            panel.showNotification();
            //JOptionPane.showMessageDialog(this, "Tên phân loại hàng hóa không được để trống!!!");            
            txt_tenloai.requestFocus();
            return;
        }
        else            
            if(idxSuaCTLH ==-1 && db.getChiTietLoaiHangs().get(t->t.getMaHang().equalsIgnoreCase(maHH) && t.getTenLoai().trim().equalsIgnoreCase(tenLoai))!=null)
            {
                //JOptionPane.showMessageDialog(this, "Tên phân loại của hàng hóa này đã tồn tại!!!");
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Tên phân loại của hàng hóa này đã tồn tại!!!");
            panel.showNotification();
                txt_tenloai.setText("");
                txt_tenloai.requestFocus();
                return;
            }
        try
        {
            giaMacDinh = Integer.parseInt(txt_giaMacDinh.getText().trim());
            if(giaMacDinh < 1)
            {
                //JOptionPane.showMessageDialog(this, "Giá mặt định phải là số nguyên lớn hơn 0!!!");
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT,  "Giá mặt định phải là số nguyên lớn hơn 0!!!");
            panel.showNotification();
                txt_giaMacDinh.setText("");
                txt_giaMacDinh.requestFocus();
                return;
            }
        }catch(Exception e)
        {
            //JOptionPane.showMessageDialog(this, "Giá mặt định phải là dữ liệu kiểu số nguyên!!!");
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT,  "Giá mặt định phải là dữ liệu kiểu số nguyên!!!");
            panel.showNotification();
            txt_giaMacDinh.setText("");
            txt_giaMacDinh.requestFocus();
            return;
        }
        try
        {
            soLuongTon  = Integer.parseInt(txt_soLuongTon.getText().trim());
            if(soLuongTon < 0)
            {
                
                //JOptionPane.showMessageDialog(this, "Giá mặt định phải là số nguyên dương!!!");
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT,  "Giá mặt định phải là số nguyên dương!!!");
            panel.showNotification();
                txt_soLuongTon.setText("");
                txt_soLuongTon.requestFocus();
                return;
            }
        }catch(Exception e)
        {
            //JOptionPane.showMessageDialog(this, "Số lượng tồn phải là dữ liệu kiểu số nguyên!!!");
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT,  "Số lượng tồn phải là dữ liệu kiểu số nguyên!!!");
            panel.showNotification();
            txt_soLuongTon.setText("");
            txt_soLuongTon.requestFocus();
            return;
        }
        if(JOptionPane.showConfirmDialog(this, "Xác nhận cập nhật dữ liệu","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {        
            boolean chk;
            ChiTietLoaiHang ctlh;
            if(idxSuaCTLH == -1)
            {                
                ctlh = new ChiTietLoaiHang(maCTLH, maHH, tenLoai, giaMacDinh, soLuongTon);
                chk =  db.getChiTietLoaiHangs().insert(ctlh);            
            }
            else
            {
                ctlh = db.getChiTietLoaiHangs().get(t->t.getMaCTLH().trim().equalsIgnoreCase(maCTLH));
                ctlh.setTenLoai(tenLoai);
                ctlh.setGiaMacDinh(giaMacDinh);
                ctlh.setSoLuongTon(soLuongTon);
                chk = db.getChiTietLoaiHangs().update(ctlh);
            }                         
            if(chk)            
            {                                         
                //JOptionPane.showMessageDialog(this, "Thao tác thành công");   
                Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT,  "Thao tác thành công");
            panel.showNotification();
                if(idxSuaCTLH==-1)
                    dtm_hhLoai.addRow(ctlh.getParameter("MaHang"));
                else
                {
                    dtm_hhLoai.removeRow(idxSuaCTLH);
                    dtm_hhLoai.insertRow(idxSuaCTLH, ctlh.getParameter("MaHang"));                    
                }                
                resetTextCTLH();
            }
            else
                //JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi, vui lòng thử lại!");
            {
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT,  "Đã xảy ra lỗi, vui lòng thử lại!");
            panel.showNotification();
            }
        }
    }//GEN-LAST:event_btn_capnhatCTLHActionPerformed

    private void btn_xoaCTLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaCTLHActionPerformed
        // TODO add your handling code here:     
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        String tenHH = dtm_hanghoa.getValueAt(idxSua, 1).toString();
        String tenLoai = dtm_hhLoai.getValueAt(idxSuaCTLH, 1).toString();
        if(JOptionPane.showConfirmDialog(this, "Xác nhận xóa loại '"+tenLoai+"' của hàng hóa '"+tenHH+"'?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {      
            String maCTLH = txt_maCTLH.getText().trim();
            ChiTietLoaiHang ctlh = db.getChiTietLoaiHangs().get(t->t.getMaCTLH().trim().equalsIgnoreCase(maCTLH));
            if(db.getChiTietLoaiHangs().delete(ctlh))
            {                
                dtm_hhLoai.removeRow(idxSuaCTLH);
                resetTextCTLH();
                //JOptionPane.showMessageDialog(this, "Xóa thành công!!!");
                Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Xóa thành công!!!");
            panel.showNotification();
            }
            else
                //JOptionPane.showMessageDialog(this, "Xóa không thành công!!!");
            {
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Xóa không thành công!!!");
            panel.showNotification();
            }
        }
    }//GEN-LAST:event_btn_xoaCTLHActionPerformed

    private void btn_huyCTLHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyCTLHActionPerformed
        // TODO add your handling code here:                
        if(JOptionPane.showConfirmDialog(this, "Xác nhận hoàn tác?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            resetTextCTLH();
        }
    }//GEN-LAST:event_btn_huyCTLHActionPerformed

    private void txt_maCTLHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_maCTLHKeyReleased
        // TODO add your handling code here:
        checkInputCTLH();
    }//GEN-LAST:event_txt_maCTLHKeyReleased

    private void txt_giaMacDinhKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_giaMacDinhKeyReleased
        // TODO add your handling code here:
        checkInputCTLH();
    }//GEN-LAST:event_txt_giaMacDinhKeyReleased

    private void txt_giaMacDinhKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_giaMacDinhKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()<'0' || evt.getKeyChar() > '9')
            evt.consume();
    }//GEN-LAST:event_txt_giaMacDinhKeyTyped

    private void txt_soLuongTonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soLuongTonKeyReleased
        // TODO add your handling code here:
        checkInputCTLH();
    }//GEN-LAST:event_txt_soLuongTonKeyReleased

    private void txt_soLuongTonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soLuongTonKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()<'0' || evt.getKeyChar() > '9')
            evt.consume();
    }//GEN-LAST:event_txt_soLuongTonKeyTyped

    private void txt_tenloaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_tenloaiKeyReleased
        // TODO add your handling code here:
        checkInputCTLH();
    }//GEN-LAST:event_txt_tenloaiKeyReleased

    private void btn_capNhatGiaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatGiaMHActionPerformed
        // TODO add your handling code here:             
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        String maCTLH = txt_maCTLH.getText().trim();
        String tenLoai = txt_tenloai.getText().trim();    
        int giaBan, dieuKien;              
        try
        {
            giaBan = Integer.parseInt(txt_giaBan.getText().trim());
            if(giaBan < 1)
            {
                //JOptionPane.showMessageDialog(this, "Giá bán phải là số nguyên lớn hơn 0!!!");
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Giá bán phải là số nguyên lớn hơn 0!!!");
            panel.showNotification();
                txt_giaBan.setText("");
                txt_giaBan.requestFocus();
                return;
            }
        }catch(Exception e)
        {
           // JOptionPane.showMessageDialog(this, "Giá bán phải là dữ liệu kiểu số nguyên!!!");
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Giá bán phải là dữ liệu kiểu số nguyên!!!");
            panel.showNotification();
            txt_giaBan.setText("");
            txt_giaBan.requestFocus();
            return;
        }
        try
        {
            dieuKien  = Integer.parseInt(txt_dieukien.getText().trim());
            if(dieuKien < 0)
            {
                //JOptionPane.showMessageDialog(this, "Số lượng tối thiểu phải là số không âm!!!");
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Số lượng tối thiểu phải là số không âm!!!");
            panel.showNotification();
                txt_dieukien.setText("");
                txt_dieukien.requestFocus();
                return;
            }
        }catch(Exception e)
        {
            //JOptionPane.showMessageDialog(this, "Số lượng tối thiểu phải là dữ liệu kiểu số nguyên!!!");
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Số lượng tối thiểu phải là dữ liệu kiểu số nguyên!!!");
            panel.showNotification();
            txt_dieukien.setText("");
            txt_dieukien.requestFocus();
            return;
        }
        if(JOptionPane.showConfirmDialog(this, "Xác nhận cập nhật dữ liệu","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {        
            boolean chk;
            GiaMatHang gmh;
            if(idxSuaGMH == -1)
            {                                
                gmh = new GiaMatHang(maCTLH, giaBan, dieuKien);
                chk =  db.getGiaMatHangs().insert(gmh);
            }
            else
            {
                System.out.println("vào");
                int dk = Integer.parseInt(dtm_hhGMH.getValueAt(idxSuaGMH, 2).toString());
                gmh  = db.getGiaMatHangs().get(t->t.getMaCTLH().trim().equalsIgnoreCase(maCTLH) && t.checkDieuKien(dk));
                gmh.setGiaBan(giaBan);
                gmh.setDieuKien(dieuKien);                
                chk = db.getGiaMatHangs().update(gmh);
            }                         
            if(chk)            
            {                                                            
                if(idxSuaGMH==-1)
                    dtm_hhGMH.addRow(gmh.getParameter());
                else
                {
                    dtm_hhGMH.removeRow(idxSuaGMH);
                    dtm_hhGMH.insertRow(idxSuaGMH, gmh.getParameter());                    
                }     
                //JOptionPane.showMessageDialog(this, "Thao tác thành công");
                Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Thao tác thành công");
            panel.showNotification();
                resetTextGMH();
            }
            else
                //JOptionPane.showMessageDialog(this, "Đã tồn tại mức giá có số lượng tối thiểu = "+dieuKien);
            {
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Đã tồn tại mức giá có số lượng tối thiểu = "+dieuKien);
            panel.showNotification();
            
            }
        }
    }//GEN-LAST:event_btn_capNhatGiaMHActionPerformed

    private void btn_xoaGiaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaGiaMHActionPerformed
        // TODO add your handling code here:              
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        String tenHH = txt_tenHangHoa.getText();
        String tenLoai = dtm_hhLoai.getValueAt(idxSuaGMH, 1).toString();        
        int dieukien = Integer.parseInt(dtm_hhGMH.getValueAt(idxSuaGMH, 2).toString());
        if(JOptionPane.showConfirmDialog(this, "Xác nhận xóa loại giá có điều kiện = "+dieukien+" của hàng hóa '"+tenHH+"' loại '"+tenLoai+"'?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {      
            String maCTLH = txt_maCTLH.getText();
            GiaMatHang gmh = db.getGiaMatHangs().get(t->t.getMaCTLH().trim().equalsIgnoreCase(maCTLH) && t.checkDieuKien(dieukien));
            if(db.getGiaMatHangs().delete(gmh))
            {                
                dtm_hhGMH.removeRow(idxSuaGMH);
                resetTextGMH();
                //JOptionPane.showMessageDialog(this, "Xóa thành công!!!");
                 Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, "Xóa thành công!!!");
            panel.showNotification();
            }
            else
                //JOptionPane.showMessageDialog(this, "Xóa không thành công!!!");
            {
            
                Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Xóa không thành công!!!");
            panel.showNotification();
            }
        }
    }//GEN-LAST:event_btn_xoaGiaMHActionPerformed

    private void btn_huyGiaMHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyGiaMHActionPerformed
        // TODO add your handling code here:                
        if(JOptionPane.showConfirmDialog(this, "Xác nhận hoàn tác?","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            resetTextGMH();
        }
    }//GEN-LAST:event_btn_huyGiaMHActionPerformed

    private void txt_dieukienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dieukienKeyReleased
        // TODO add your handling code here:
        checkInputGiaMatHang();
    }//GEN-LAST:event_txt_dieukienKeyReleased

    private void txt_dieukienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dieukienKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()<'0' || evt.getKeyChar() > '9')
            evt.consume();
    }//GEN-LAST:event_txt_dieukienKeyTyped

    private void txt_giaBanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_giaBanKeyReleased
        // TODO add your handling code here:
        checkInputGiaMatHang();
    }//GEN-LAST:event_txt_giaBanKeyReleased

    private void txt_giaBanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_giaBanKeyTyped
        // TODO add your handling code here:
        if(evt.getKeyChar()<'0' || evt.getKeyChar() > '9')
            evt.consume();
    }//GEN-LAST:event_txt_giaBanKeyTyped
    void resetText()
    {
        idxSua = -1;
        String maHH = taoMaHangHoa();
        txt_maHangHoa.setText(maHH);
        txt_tenHangHoa.setText("");        
        txt_donViTinh.setText("");
        label_anhHangHoa.setText("Ảnh hàng hóa");
        label_anhHangHoa.setIcon(null);
        txt_anh.setText("");
        txt_path.setText("");
        btn_capnhat.setText("Thêm");
        btn_xoa.setEnabled(false);
        btn_huy.setEnabled(false);    
        resetTextCTLH();
        loadDataCTLH();
        btn_capnhatCTLH.setEnabled(false);
        loadDataGiaMatHang();
    }
    private String taoMaHangHoa()
    {
        int sl =1;
        while(true)
        {
            String ma = "HH00"+ String.valueOf(db.getHangHoas().size()+sl);
            if(db.getHangHoas().get(t->t.getMaHang().trim().equalsIgnoreCase(ma))==null)
            {
                return ma;
            }
            sl++;
        }
    }
    private String taoMaChiTietLoaiHang()
    {
         int sl =1;
        while(true)
        {
            String ma = "CTLH00"+ String.valueOf(db.getChiTietLoaiHangs().size()+sl);
            if(db.getChiTietLoaiHangs().get(t->t.getMaHang().trim().equalsIgnoreCase(ma))==null)
            {
                return ma;
            }
            sl++;
        }
    }
    void resetTextCTLH()
    {
        String maCTLH = taoMaChiTietLoaiHang();
        txt_maCTLH.setText(maCTLH);
        txt_tenloai.setText("");
        txt_giaMacDinh.setText("");
        txt_soLuongTon.setText("");
        idxSuaCTLH =-1;
        btn_xoaCTLH.setEnabled(false);
        btn_huyCTLH.setEnabled(false);
        btn_capnhatCTLH.setText("Thêm");
        btn_capNhatGiaMH.setEnabled(false);
        resetTextGMH();
        loadGiaMatHangThuocHangHoa();        
    }
    void resetTextGMH()
    {
        txt_giaBan.setText("");
        txt_dieukien.setText("");
        btn_xoaGiaMH.setEnabled(false);
        btn_huyGiaMH.setEnabled(false);
        btn_capNhatGiaMH.setText("Thêm");
        idxSuaGMH=-1;
    }
    void loadGiaMatHangThuocHangHoa()
    {
        Vector data = new Vector();
        String maHH = txt_maHangHoa.getText();
        db.getGiaMatHangs().parallelStream().filter(t->t.getChiTietLoaiHang().getHangHoa().getMaHang().trim().equals(maHH)).forEach(g->data.add(g.getParameter()));
        dtm_hhGMH.setDataVector(data, headerGMH);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button btn_capNhatGiaMH;
    private button.Button btn_capnhat;
    private button.Button btn_capnhatCTLH;
    private button.Button btn_chonFileAnh;
    private button.Button btn_huy;
    private button.Button btn_huyCTLH;
    private button.Button btn_huyGiaMH;
    private button.Button btn_xoa;
    private button.Button btn_xoaCTLH;
    private button.Button btn_xoaGiaMH;
    private combo_suggestion.ComboBoxSuggestion cbo_loaiHang;
    private checkbox.JCheckBoxCustom chk_tatca;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_anhHangHoa;
    private table.TableScrollButton tableScrollButton1;
    private table.TableScrollButton tableScrollButton2;
    private table.TableScrollButton tableScrollButton3;
    private javax.swing.JTable tbl_CTLH;
    private javax.swing.JTable tbl_giaMatHang;
    private javax.swing.JTable tbl_hangHoa;
    private javax.swing.JTextField txt_anh;
    private textfield.TextField txt_dieukien;
    private textfield.TextField txt_donViTinh;
    private textfield.TextField txt_giaBan;
    private textfield.TextField txt_giaMacDinh;
    private textfield.TextField txt_maCTLH;
    private textfield.TextField txt_maHangHoa;
    private javax.swing.JTextField txt_path;
    private textfield.TextField txt_soLuongTon;
    private textfield.TextField txt_tenHangHoa;
    private textfield.TextField txt_tenloai;
    // End of variables declaration//GEN-END:variables
}
