/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Model.DBQuanLyVatTuNongNghiep;
import Model.NhaCungCap;
import Model.NhanVien;
import Model.PhieuDatHang;
import Model.PhieuGiaoHang;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import table.TableCustom;

/**
 *
 * @author Admin
 */
public class QuanLyPhieuDatHang_GUI extends javax.swing.JPanel {

    DefaultTableModel dtm =null;
    Vector header = new Vector();
    DBQuanLyVatTuNongNghiep db = null;
    NhaCungCap ncc =  null;
    PhieuDatHang phieuDatHang = null;
    NhanVien user;
    DefaultTableModel dtm_ctdh =null;
    Vector header_ctdh = new Vector();
    Vector<String> tblNames = new Vector<String>();
    Vector<String> fiedlNames = new Vector<String>();
    public QuanLyPhieuDatHang_GUI(DBQuanLyVatTuNongNghiep db,NhanVien user ) {
        initComponents();
        this.db = db;
        this.user = user;                
        khoiTao();
    }

    private void khoiTao() {
                        
        header.add("Số đơn đặt hàng");        
        header.add("Mã nhà cung cấp");
        header.add("Mã nhân viên");
        header.add("Ngày đặt");
        header.add("Thành tiền");
        dtm = new DefaultTableModel();        
        tbl_phieuDatHangs.setModel(dtm);        
        dtm.setDataVector(db.getPhieuDatHangs().getData(), header);
        
        header_ctdh.add("Mã");
        header_ctdh.add("Đơn giá");
        header_ctdh.add("Số lượng");
        header_ctdh.add("Tên loại");
        header_ctdh.add("Tên hàng");        
        dtm_ctdh = new DefaultTableModel();
        tbl_chiTietPhieuDat.setModel(dtm_ctdh);                
        tblNames.add("ChiTietDatHang");
        tblNames.add("chiTietLoaiHang");
        tblNames.add("hangHoa");
        fiedlNames.add("SoDonDatHang");
        fiedlNames.add("MaCTLH");
        fiedlNames.add("DonGia");
        fiedlNames.add("SoLuong");
        fiedlNames.add("TenLoai");
        fiedlNames.add("TenHang");

        dtm_ctdh.setDataVector(db.getChiTietDatHangs().includesAs(tblNames, fiedlNames) ,header_ctdh);
        cbo_ncc.setSelectedIndex(-1);
        cbo_ncc.addItem("Tất cả");
       db.getNhaCungCaps().forEach(ncc->cbo_ncc.addItem(ncc.getMaNCC()+" - "+ncc.getTenNCC()));
       cbo_ncc.setEnabled(false);
       chk_tatCa.setSelected(true);
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        TableCustom.apply(jScrollPane2, TableCustom.TableType.MULTI_LINE);       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_phieuDatHangs = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_chiTietPhieuDat = new javax.swing.JTable();
        cbo_ncc = new combobox.Combobox();
        chk_tatCa = new checkbox.JCheckBoxCustom();

        setBackground(new java.awt.Color(255, 255, 255));

        tbl_phieuDatHangs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_phieuDatHangs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_phieuDatHangsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_phieuDatHangs);

        tbl_chiTietPhieuDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_chiTietPhieuDat);

        cbo_ncc.setLabeText("Nhà cung cấp");
        cbo_ncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_nccActionPerformed(evt);
            }
        });

        chk_tatCa.setText("Tất cả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(chk_tatCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(cbo_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(889, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_tatCa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(534, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addComponent(jScrollPane2))
                    .addContainerGap(44, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_phieuDatHangsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_phieuDatHangsMouseClicked
        // TODO add your handling code here:
        int row = tbl_phieuDatHangs.getSelectedRow();
        if(row==-1)
        return;
        String soDDHSelect = dtm.getValueAt(row, 0).toString().trim();
        phieuDatHang = db.getPhieuDatHangs().get(p->p.getSoDonDatHang().trim().equals(soDDHSelect));
        dtm_ctdh.setDataVector(phieuDatHang.getChiTietDatHangs().getData(), header_ctdh);

        int demSL = 0;
        for (PhieuGiaoHang pgh : phieuDatHang.getPhieuGiaoHangs())
        {
            if(pgh.getTrangThai().equals("Bị hủy"))
            continue;
            demSL+=pgh.getTongSL();
        }        
    }//GEN-LAST:event_tbl_phieuDatHangsMouseClicked

    private String getMaNhaCungCapSelected()
    {
        return cbo_ncc.getSelectedItem().toString().split(" - ")[0];
    }
    private void cbo_nccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_nccActionPerformed
        // TODO add your handling code here:
        if(cbo_ncc.getSelectedIndex()<0)
            return;
        if(cbo_ncc.getSelectedIndex()==0)
        {
            dtm.setDataVector(db.getPhieuDatHangs().getData(), header);
            dtm_ctdh.setDataVector(db.getChiTietDatHangs().includesAs(tblNames, fiedlNames) ,header_ctdh);
            return;
        }
        String maNCC = getMaNhaCungCapSelected();
        NhaCungCap n = db.getNhaCungCaps().get(ncc->ncc.getMaNCC().equals(maNCC));               
        dtm.setDataVector(n.getPhieuDatHangs().getData(),header);
        dtm_ctdh.setRowCount(0);
        dtm_ctdh.setDataVector(db.getChiTietDatHangs().getData(ct->ct.getPhieuDatHang().getMaNCC().trim().equalsIgnoreCase(maNCC.trim()), tblNames, fiedlNames), header);
    }//GEN-LAST:event_cbo_nccActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private combobox.Combobox cbo_ncc;
    private checkbox.JCheckBoxCustom chk_tatCa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_chiTietPhieuDat;
    private javax.swing.JTable tbl_phieuDatHangs;
    // End of variables declaration//GEN-END:variables

    
}
