/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.ChiTietLoaiHang;
import Model.DBQuanLyVatTuNongNghiep;
import Model.NhaCungCap;
import java.awt.Color;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaswingdev.Notification;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;
import table.TableCustom;
import textfield.EventCallBack;
import textfield.EventTextField;
import textfield.TextFieldAnimation;

/**
 *
 * @author Admin
 */
public class SoSanhGia extends javax.swing.JFrame {

    /**
     * Creates new form SoSanhGia
     */
    DBQuanLyVatTuNongNghiep db = null;   
    DefaultTableModel dtm =null;
    Vector header = new Vector();
    Vector<String> tblNames = new Vector<String>();
    Vector<String> fiedlNames = new Vector<String>();
    public SoSanhGia(DBQuanLyVatTuNongNghiep db) {
        initComponents();
        this.db = db;
        khoiTao();
        dtm.setDataVector(db.getNguonHangs().includesAs(tblNames, fiedlNames), header);
    }
    
    public SoSanhGia(DBQuanLyVatTuNongNghiep db, ChiTietLoaiHang ctlh) {
        initComponents();
        this.db = db;   
        khoiTao();            
        for(int i = 0 ; i< cbo_loaiHang.getItemCount();i++)        
            if(cbo_loaiHang.getItemAt(i).equals(ctlh.getHangHoa().getLoaiHang().getTenLoaiHang()))
            {                 
                cbo_loaiHang.setSelectedIndex(i);                
                break;
            }
        for(int i = 0;i<cbo_sanPham.getItemCount();i++)
            if(cbo_sanPham.getItemAt(i).equals(ctlh.getHangHoa().getTenHang()))
            {
                cbo_sanPham.setSelectedIndex(i);
                break;
            }
        for(int i = 0;i<cbo_loaiSanPham.getItemCount();i++)
            if(cbo_loaiSanPham.getItemAt(i).equals(ctlh.getTenLoai()))
            {
                cbo_loaiSanPham.setSelectedIndex(i);
                break;
            }      
        cbo_loaiSanPhamActionPerformed(null);   
        
    }
    
    private void khoiTao()
    {
        dtm = new DefaultTableModel();
        tbl_nguonHang.setModel(dtm);   
        getContentPane().setBackground(new Color(245, 245, 245));
        tblNames.add("NguonHang");
        tblNames.add("nhaCungCap");
        tblNames.add("chiTietLoaiHang");
        tblNames.add("hangHoa");
        fiedlNames.add("MaNCC");
        fiedlNames.add("TenNCC");
        fiedlNames.add("MaCTLH");
        fiedlNames.add("GiaNhap");
        fiedlNames.add("TenLoai");
        fiedlNames.add("TenHang");
        
        header.add("Mã NCC");
        header.add("Mã CTLH");
        header.add("Giá nhập");        
        header.add("Tên nhà cung cấp");  
        header.add("Loại hàng");   
        header.add("Tên hàng");
        dtm.setColumnIdentifiers(header);        
        db.getLoaiHangs().forEach(t->cbo_loaiHang.addItem(t.getTenLoaiHang()));
        TableCustom.apply(jScrollPane1, TableCustom.TableType.MULTI_LINE);
        
       txt_timKiem.addEvent(new EventTextField(){
            @Override
            public void onPressed(EventCallBack call) {
                try {
                    String value = txt_timKiem.getText().toLowerCase();
                    dtm.setDataVector(db.getNguonHangs().getData(nh->nh.getMaNCC().toLowerCase().contains(value)
                            ||nh.getMaCTLH().toLowerCase().contains(value)
                            ||nh.getNhaCungCap().getTenNCC().toLowerCase().contains(value)
                            ||nh.getChiTietLoaiHang().getTenLoai().toLowerCase().contains(value)
                            ||nh.getChiTietLoaiHang().getHangHoa().getTenHang().toLowerCase().contains(value)
                            ||String.valueOf(nh.getGiaNhap()).contains(value),tblNames,fiedlNames), header);                    
                    Thread.sleep(1000);
                    call.done();
                } catch (InterruptedException ex) {
                    Logger.getLogger(QuanLyHoaDon_GUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void onCancel() {
                
            }
            
        });
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbo_loaiHang = new combobox.Combobox();
        cbo_sanPham = new combobox.Combobox();
        cbo_loaiSanPham = new combobox.Combobox();
        jPanel1 = new javax.swing.JPanel();
        txt_timKiem = new textfield.TextFieldAnimation();
        tableScrollButton1 = new table.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nguonHang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbo_loaiHang.setLabeText("Loại hàng");
        cbo_loaiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_loaiHangActionPerformed(evt);
            }
        });

        cbo_sanPham.setLabeText("Hàng hóa");
        cbo_sanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_sanPhamActionPerformed(evt);
            }
        });

        cbo_loaiSanPham.setLabeText("Phân loại sản phẩm");
        cbo_loaiSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_loaiSanPhamActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 28, 68));

        txt_timKiem.setHintText("Tìm kiếm ...");
        txt_timKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_nguonHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbl_nguonHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_nguonHang.setRowHeight(30);
        jScrollPane1.setViewportView(tbl_nguonHang);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 746, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(49, 49, 49)
                            .addComponent(cbo_loaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(89, 89, 89)
                            .addComponent(cbo_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(60, 60, 60)
                            .addComponent(cbo_loaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_loaiHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_sanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbo_loaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    ChiTietLoaiHang getChiTietLoaiHang(String tenHang,String tenLoaiSP)
    {
        return db.getChiTietLoaiHangs().get(t->t.getHangHoa().getTenHang()
                .equalsIgnoreCase(tenHang)&&t.getTenLoai().equalsIgnoreCase(tenLoaiSP));                
    }
    ChiTietLoaiHang getChiTietLoaiHang(String maCTLH)
    {
        return db.getChiTietLoaiHangs().get(t->t.getMaCTLH().equalsIgnoreCase(maCTLH));                
    }
    
    private void cbo_loaiHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_loaiHangActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        cbo_loaiSanPham.setSelectedIndex(-1);
        if(cbo_loaiHang.getSelectedIndex()<0)
        return;
        cbo_sanPham.removeAllItems();
        try
        {
            String tenLoai = cbo_loaiHang.getSelectedItem().toString();
            db.getLoaiHangs().get(t->t.getTenLoaiHang().equalsIgnoreCase(tenLoai)).getHangHoas().forEach(h->cbo_sanPham.addItem(h.getTenHang()));
        }
        catch(Exception e)
        {
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Đã xảy ra lỗi, vui lòng thử lại!!!");
            panel.showNotification();
            //JOptionPane.showMessageDialog(this,"Đã xảy ra lỗi, vui lòng thử lại!!!");
        }
    }//GEN-LAST:event_cbo_loaiHangActionPerformed

    private void cbo_sanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_sanPhamActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
         cbo_loaiSanPham.setSelectedIndex(-1);
        cbo_loaiSanPham.removeAllItems();
        if(cbo_sanPham.getSelectedIndex()<0)
        return;
        try{
            String tenSanPham;
            tenSanPham = cbo_sanPham.getSelectedItem().toString();
            db.getHangHoas().get(t->t.getTenHang().equalsIgnoreCase(tenSanPham)).getChiTietLoaiHangs().forEach(l->cbo_loaiSanPham.addItem(l.getTenLoai()));
            cbo_loaiSanPhamActionPerformed(null);
        }catch(Exception e)
        {
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Đã xảy ra lỗi, vui lòng thử lại!!!");
            panel.showNotification();
            //JOptionPane.showMessageDialog(this,"Đã xảy ra lỗi, vui lòng thử lại!!!");
        }
    }//GEN-LAST:event_cbo_sanPhamActionPerformed

    private void cbo_loaiSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_loaiSanPhamActionPerformed
        // TODO add your handling code here:
        try
        {
            dtm.setRowCount(0);
        }catch(Exception e){}
        try
        {
            ChiTietLoaiHang ctlh = getChiTietLoaiHang(cbo_sanPham.getSelectedItem().toString(),cbo_loaiSanPham.getSelectedItem().toString());
            dtm.setDataVector(ctlh.getNguonHangs().getData(n->n.getChiTietLoaiHang().getMaCTLH().equals(ctlh.getMaCTLH()), tblNames, fiedlNames), header);                                    
        } catch(Exception e){}
    }//GEN-LAST:event_cbo_loaiSanPhamActionPerformed

    private void txt_timKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    
//     public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SoSanhGia(new DBQuanLyVatTuNongNghiep(),new DBQuanLyVatTuNongNghiep().getChiTietLoaiHangs().get(6)).setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private combobox.Combobox cbo_loaiHang;
    private combobox.Combobox cbo_loaiSanPham;
    private combobox.Combobox cbo_sanPham;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private table.TableScrollButton tableScrollButton1;
    private javax.swing.JTable tbl_nguonHang;
    private textfield.TextFieldAnimation txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
