/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Model.DBQuanLyVatTuNongNghiep;
import Model.PhieuGiaoHang;
import java.awt.Color;
import java.awt.Component;
import javaswingdev.Notification;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Admin
 */
public class TuChoiPhieuGiaoHang_GUI extends javax.swing.JFrame {

    /**
     * Creates new form TuChoiPhieuGiaoHang_GUi
     */
    PhieuGiaoHang pgh;
    DBQuanLyVatTuNongNghiep db;
    QuanLyPhieuGiaoHang_GUI qlgh;
    
    public TuChoiPhieuGiaoHang_GUI(QuanLyPhieuGiaoHang_GUI qlgh,DBQuanLyVatTuNongNghiep db,PhieuGiaoHang pgh) {
        initComponents();
        this.pgh = pgh;
        this.db = db;
        this.qlgh = qlgh;
        label_soPG.setText(this.pgh.getSoPhieuGiao());
        textPane.setEnabled(false);
        getContentPane().setBackground(new Color(255, 255, 255));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        label_soPG = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panel_lydo = new javax.swing.JPanel();
        chk_1 = new checkbox.JCheckBoxCustom();
        chk_2 = new checkbox.JCheckBoxCustom();
        chk_3 = new checkbox.JCheckBoxCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        textPane = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_hủy = new button.Button();
        btn_xacNhanHuy = new button.Button();
        chk_khac = new checkbox.JCheckBoxCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Xác nhận từ chối phiếu giao hàng");

        label_soPG.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_soPG.setText("PGH001");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("?");

        jLabel4.setText("Vui lòng chọn lý do từ chối:");

        panel_lydo.setBackground(new java.awt.Color(255, 255, 255));

        chk_1.setBackground(new java.awt.Color(12, 87, 118));
        chk_1.setText("Xuất hiện sai sót về mặt số lượng");

        chk_2.setBackground(new java.awt.Color(12, 87, 118));
        chk_2.setText("Hàng hóa không đứng yêu cầu");

        chk_3.setBackground(new java.awt.Color(12, 87, 118));
        chk_3.setText("Hàng hóa bị hư hỏng");

        javax.swing.GroupLayout panel_lydoLayout = new javax.swing.GroupLayout(panel_lydo);
        panel_lydo.setLayout(panel_lydoLayout);
        panel_lydoLayout.setHorizontalGroup(
            panel_lydoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lydoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_lydoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chk_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_lydoLayout.setVerticalGroup(
            panel_lydoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_lydoLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(chk_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        textPane.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textPaneKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(textPane);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Lưu ý: khi bạn nhấn xác nhận, đồng nghĩa với việc phiếu giao hàng này");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("sẽ được hủy và hoàn trả lại về cho nhà cung cấp");

        btn_hủy.setText("Hủy");
        btn_hủy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_hủy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hủyActionPerformed(evt);
            }
        });

        btn_xacNhanHuy.setBackground(new java.awt.Color(0, 28, 68));
        btn_xacNhanHuy.setForeground(new java.awt.Color(255, 255, 255));
        btn_xacNhanHuy.setText("Xác nhận hủy");
        btn_xacNhanHuy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_xacNhanHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xacNhanHuyActionPerformed(evt);
            }
        });

        chk_khac.setBackground(new java.awt.Color(0, 28, 68));
        chk_khac.setText("Khac");
        chk_khac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_khacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_soPG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(chk_khac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(panel_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btn_hủy, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_xacNhanHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_soPG)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_lydo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_khac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_hủy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xacNhanHuy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textPaneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textPaneKeyTyped
        // TODO add your handling code here:
        if(textPane.getText().length()>50)
            evt.consume();
    }//GEN-LAST:event_textPaneKeyTyped

    private void btn_hủyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hủyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btn_hủyActionPerformed

    private void btn_xacNhanHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xacNhanHuyActionPerformed
        // TODO add your handling code here:
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        String lydo = layLyDo();
        if(lydo.equals(""))
        {
            //JOptionPane.showMessageDialog(this, "Phải có ít nhất 1 lý do hủy phiếu giao hàng!!!");
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, "Phải có ít nhất 1 lý do hủy phiếu giao hàng!!!");
            panel.showNotification();
            return;
        }
        pgh.setTrangThai("Bị hủy");
        pgh.setGhiChu(lydo);
        System.out.println(lydo);
        if(db.getPhieuGiaoHangs().update(pgh))
            //JOptionPane.showMessageDialog(this, "Thao tác thành công");
        {
            Notification panel = new Notification(frame, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT,  "Thao tác thành công");
            panel.showNotification();
        }
        else
        {
            Notification panel = new Notification(frame, Notification.Type.WARNING, Notification.Location.TOP_RIGHT,  "Hủy phiếu giao hàng thất bại");
            panel.showNotification();
        }
            //JOptionPane.showMessageDialog(this, "Hủy phiếu giao hàng thất bại");
        this.qlgh.locTheoTrangThai();
        this.qlgh.setsetEnabledFalse();
        this.setVisible(false);
    }//GEN-LAST:event_btn_xacNhanHuyActionPerformed

    private void chk_khacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_khacActionPerformed
        // TODO add your handling code here:
        textPane.setEnabled(!textPane.isEnabled());
    }//GEN-LAST:event_chk_khacActionPerformed

    private String layLyDo()
    {
        String lydo = "";
        for (Component com : panel_lydo.getComponents()) {
            JCheckBox chk = (JCheckBox)com;
            if(chk.isSelected())
                lydo+=chk.getText()+". ";
        }
        if(chk_khac.isSelected())
            lydo+=textPane.getText().trim()+".";
        return lydo;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TuChoiPhieuGiaoHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TuChoiPhieuGiaoHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TuChoiPhieuGiaoHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TuChoiPhieuGiaoHang_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TuChoiPhieuGiaoHang_GUI(new DBQuanLyVatTuNongNghiep(), new DBQuanLyVatTuNongNghiep().getPhieuGiaoHangs().get(0)).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private button.Button btn_hủy;
    private button.Button btn_xacNhanHuy;
    private checkbox.JCheckBoxCustom chk_1;
    private checkbox.JCheckBoxCustom chk_2;
    private checkbox.JCheckBoxCustom chk_3;
    private checkbox.JCheckBoxCustom chk_khac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_soPG;
    private javax.swing.JPanel panel_lydo;
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
