/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyNhaCungCap;

import MeThods.KetNoi;
import Model.DBQuanLyVatTuNongNghiep;
import Model.NhaCungCap;
import Model.PhieuDatHang;
import Model.PhieuGiaoHang;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLyDonDatHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyDonDatHang
     */
    DefaultTableModel dtm =null;
    Vector header = new Vector();
    DBQuanLyVatTuNongNghiep db = null;
    NhaCungCap ncc =  null;
    PhieuDatHang phieuDatHang = null;
    
    DefaultTableModel dtm_ctdh =null;
    Vector header_ctdh = new Vector();
    String[] remove_fieldNames = new String[]{
            "MaNCC",
            "MaNV",
        };
    public QuanLyDonDatHang(DBQuanLyVatTuNongNghiep db, NhaCungCap ncc) {
        initComponents();
        
        this.db = db;
        this.ncc = ncc;
        lable_xinchao.setText("Xin chào "+this.ncc.getTenNCC());
        header.add("Số đơn đặt hàng");
        header.add("Ngày đặt");
        header.add("Tổng số lượng");
        header.add("Thành tiền");
        dtm = new DefaultTableModel();        
        tbl_phieuDatHangs.setModel(dtm);        
        dtm.setDataVector(ncc.getPhieuDatHangs().getData(remove_fieldNames), header);
        
        
        header_ctdh.add("Mã");
        header_ctdh.add("Đơn giá");
        header_ctdh.add("Số lượng");
        dtm_ctdh = new DefaultTableModel();
        tbl_chiTietPhieuDat.setModel(dtm_ctdh);
        dtm_ctdh.setColumnIdentifiers(header_ctdh);
        
        btn_taoPhieuGiao.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        QuanLyDatHang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_phieuDatHangs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_taoPhieuGiao = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_chiTietPhieuDat = new javax.swing.JTable();
        QuanLyGiaoHang = new javax.swing.JPanel();
        lable_xinchao = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_phieuDatHangs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_phieuDatHangs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_phieuDatHangsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_phieuDatHangs);

        jLabel1.setText("DANH SÁCH CÁC ĐƠN ĐẶT HÀNG");

        btn_taoPhieuGiao.setText("Tạo phiếu giao hàng");
        btn_taoPhieuGiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_taoPhieuGiaoActionPerformed(evt);
            }
        });

        tbl_chiTietPhieuDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbl_chiTietPhieuDat);

        javax.swing.GroupLayout QuanLyDatHangLayout = new javax.swing.GroupLayout(QuanLyDatHang);
        QuanLyDatHang.setLayout(QuanLyDatHangLayout);
        QuanLyDatHangLayout.setHorizontalGroup(
            QuanLyDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyDatHangLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_taoPhieuGiao)
                .addGap(46, 46, 46))
            .addGroup(QuanLyDatHangLayout.createSequentialGroup()
                .addGroup(QuanLyDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(QuanLyDatHangLayout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(QuanLyDatHangLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        QuanLyDatHangLayout.setVerticalGroup(
            QuanLyDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, QuanLyDatHangLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btn_taoPhieuGiao)
                .addGap(29, 29, 29)
                .addGroup(QuanLyDatHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Quản lý đặt hàng", QuanLyDatHang);

        javax.swing.GroupLayout QuanLyGiaoHangLayout = new javax.swing.GroupLayout(QuanLyGiaoHang);
        QuanLyGiaoHang.setLayout(QuanLyGiaoHangLayout);
        QuanLyGiaoHangLayout.setHorizontalGroup(
            QuanLyGiaoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1286, Short.MAX_VALUE)
        );
        QuanLyGiaoHangLayout.setVerticalGroup(
            QuanLyGiaoHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Quản lý giao hàng", QuanLyGiaoHang);

        lable_xinchao.setText("Xin chào: Nhà cung cấp 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lable_xinchao)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lable_xinchao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_phieuDatHangsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_phieuDatHangsMouseClicked
        // TODO add your handling code here:
        int row = tbl_phieuDatHangs.getSelectedRow();
        if(row==-1)
            return;
        String soDDHSelect = dtm.getValueAt(row, 0).toString().trim();
        phieuDatHang = db.getPhieuDatHangs().get(p->p.getSoDonDatHang().trim().equals(soDDHSelect));    
        dtm_ctdh.setDataVector(phieuDatHang.getChiTietDatHangs().getData("SoDonDatHang"), header_ctdh); 
        
        int demSL = 0;
        for (PhieuGiaoHang pgh : phieuDatHang.getPhieuGiaoHangs())
        {
             if(pgh.getTrangThai().equals("Bị hủy"))
                 continue;
             demSL+=pgh.getTongSL(); 
         }        
        if(phieuDatHang.getTongSL() == demSL || phieuDatHang.getPhieuGiaoHangs().stream().filter(p-> !p.getTrangThai().equals("Bị hủy")).count()==3)
        {
            btn_taoPhieuGiao.setText("Hoàn tất giao hàng");
            btn_taoPhieuGiao.setEnabled(false);
        }
        else
        {
            btn_taoPhieuGiao.setText("Tạo phiếu giao hàng");
            btn_taoPhieuGiao.setEnabled(true);
        }
    }//GEN-LAST:event_tbl_phieuDatHangsMouseClicked

    private void btn_taoPhieuGiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_taoPhieuGiaoActionPerformed
        // TODO add your handling code here:        
        TaoPhieuGiao tpg = new TaoPhieuGiao(db,phieuDatHang);
        tpg.pack();
        tpg.setLocationRelativeTo(null);
        tpg.setVisible(true);
        tpg.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);       
    }//GEN-LAST:event_btn_taoPhieuGiaoActionPerformed
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QuanLyDonDatHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QuanLyDonDatHang(new DBQuanLyVatTuNongNghiep(),new DBQuanLyVatTuNongNghiep().getNhaCungCaps().get(0)).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel QuanLyDatHang;
    private javax.swing.JPanel QuanLyGiaoHang;
    private javax.swing.JButton btn_taoPhieuGiao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lable_xinchao;
    private javax.swing.JTable tbl_chiTietPhieuDat;
    private javax.swing.JTable tbl_phieuDatHangs;
    // End of variables declaration//GEN-END:variables
}
