/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLyNhaCungCap;

import Model.ChiTietDatHang;
import Model.ChiTietGiaoHang;
import Model.DBQuanLyVatTuNongNghiep;
import Model.PhieuDatHang;
import Model.PhieuGiaoHang;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class TaoPhieuGiao extends javax.swing.JFrame {

    /**
     * Creates new form TaoPhieuGiao
     */
    DBQuanLyVatTuNongNghiep db = null;
    PhieuDatHang phieuDatHang = null;
    DefaultTableModel dtm =null;
    Vector header = new Vector();   
    int idxSua = -1;
    public TaoPhieuGiao(DBQuanLyVatTuNongNghiep db, PhieuDatHang phieuDatHang) {
        initComponents();
        this.db = db;
        this.phieuDatHang = phieuDatHang;
        dtm = new DefaultTableModel();       
        header.add("Mã");
        header.add("Tên sản phẩm");
        header.add("Loại");
        header.add("Đơn giá");
        header.add("Số lượng");
        header.add("Tổng tiền");
        dtm = new DefaultTableModel();
        dtm.setColumnIdentifiers(header);
        tbl_chiTietGiaoHang.setModel(dtm);        
        txt_soLuongChuaGiao.setEditable(false);
        txt_soLuongDat.setEditable(false);
        btn_huy.setEnabled(false);
        btn_xoa.setEnabled(false);
        phieuDatHang.getChiTietDatHangs().forEach(ct->cbo_chiTietDatHang.addItem(ct.getMaCTLH() + " - " + ct.getChiTietLoaiHang().getTenLoai() + " - "+ct.getChiTietLoaiHang().getHangHoa().getTenHang()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbo_chiTietDatHang = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_soLuongDat = new javax.swing.JTextField();
        btn_tru = new javax.swing.JButton();
        txt_soLuong = new javax.swing.JTextField();
        btn_cong = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_chiTietGiaoHang = new javax.swing.JTable();
        btn_capNhat = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        btn_lamMoi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_soLuongChuaGiao = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbo_chiTietDatHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_chiTietDatHangActionPerformed(evt);
            }
        });

        jLabel1.setText("Chọn hàng hóa");

        jLabel2.setText("Số lượng đặt");

        btn_tru.setText("-");
        btn_tru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_truActionPerformed(evt);
            }
        });

        txt_soLuong.setText("1");
        txt_soLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_soLuongActionPerformed(evt);
            }
        });
        txt_soLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_soLuongKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_soLuongKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_soLuongKeyTyped(evt);
            }
        });

        btn_cong.setText("+");
        btn_cong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_congActionPerformed(evt);
            }
        });

        tbl_chiTietGiaoHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_chiTietGiaoHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_chiTietGiaoHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_chiTietGiaoHang);

        btn_capNhat.setText("Thêm");
        btn_capNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_capNhatActionPerformed(evt);
            }
        });

        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        btn_lamMoi.setText("Làm mới");
        btn_lamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lamMoiActionPerformed(evt);
            }
        });

        jButton1.setText("Tạo phiếu giao");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Số lượng chưa giao");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_soLuongDat, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_soLuongChuaGiao, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btn_tru)
                                .addGap(0, 0, 0)
                                .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btn_cong)
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_capNhat)
                                    .addComponent(btn_huy))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_xoa)
                                    .addComponent(btn_lamMoi)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbo_chiTietDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbo_chiTietDatHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_soLuongDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cong)
                            .addComponent(btn_tru)
                            .addComponent(jLabel3)
                            .addComponent(txt_soLuongChuaGiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_capNhat)
                            .addComponent(btn_xoa))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_lamMoi)
                            .addComponent(btn_huy))))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_truActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_truActionPerformed
        // TODO add your handling code here:
        String strsl = txt_soLuong.getText();
        if(strsl.equals("1"))
        return;
        int sl = Integer.parseInt(strsl);
        txt_soLuong.setText(String.valueOf(--sl));
    }//GEN-LAST:event_btn_truActionPerformed

    private void txt_soLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_soLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongActionPerformed

    private void txt_soLuongKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soLuongKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongKeyPressed

    private void txt_soLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_soLuongKeyReleased

    private void txt_soLuongKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_soLuongKeyTyped
        // TODO add your handling code here:
        String strsl = txt_soLuong.getText();
        if(strsl.isEmpty() && evt.getKeyChar()=='0')
        evt.consume();
        else if(evt.getKeyChar()<'0' || evt.getKeyChar() > '9')
        evt.consume();
        else
        {
            int slTon =Integer.parseInt(txt_soLuongChuaGiao.getText());
            int slInt = Integer.parseInt(strsl+String.valueOf(evt.getKeyChar()));
            if(slInt>slTon)
            evt.consume();
        }
    }//GEN-LAST:event_txt_soLuongKeyTyped

    private void btn_congActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_congActionPerformed
        // TODO add your handling code here:
        String strsl = txt_soLuong.getText();
        if(strsl.isEmpty())
        txt_soLuong.setText("1");
        else
        {
            int slTon =Integer.parseInt(txt_soLuongChuaGiao.getText());
            int sl = Integer.parseInt(strsl);
            if(sl<slTon)
            txt_soLuong.setText(String.valueOf(++sl));
        }
    }//GEN-LAST:event_btn_congActionPerformed

    private void cbo_chiTietDatHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_chiTietDatHangActionPerformed
        // TODO add your handling code here:
        ChiTietDatHang ctdh = getChiTietDatHangSelect();
        txt_soLuongDat.setText(String.valueOf(ctdh.getSoLuong()));        
        int slDaGiao = this.phieuDatHang.getSoLuongDaGiao(ctdh.getMaCTLH());
        txt_soLuongChuaGiao.setText(String.valueOf(ctdh.getSoLuong()-slDaGiao));
    }//GEN-LAST:event_cbo_chiTietDatHangActionPerformed

    private void tbl_chiTietGiaoHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_chiTietGiaoHangMouseClicked
        // TODO add your handling code here:                        
        idxSua = tbl_chiTietGiaoHang.getSelectedRow();        
        btn_capNhat.setText("Cập nhật");
        btn_huy.setEnabled(true);
        btn_xoa.setEnabled(true);
        ChiTietDatHang ctdh = getChiTietDatHangSelect();
        txt_soLuongDat.setText(String.valueOf(ctdh.getSoLuong()));
        for(int i = 0 ; i< cbo_chiTietDatHang.getItemCount();i++)        
            if(cbo_chiTietDatHang.getItemAt(i).contains(ctdh.getMaCTLH()))
            {
                cbo_chiTietDatHang.setSelectedIndex(i);                
                break;
            }   
    }//GEN-LAST:event_tbl_chiTietGiaoHangMouseClicked

    private ChiTietDatHang getChiTietDatHangSelect()
    {
        String maCTLH = getMaCTLHSelect();
        return phieuDatHang.getChiTietDatHangs().get(t->t.getMaCTLH().trim().equals(maCTLH));
    }
    private void btn_capNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_capNhatActionPerformed
        // TODO add your handling code here:
        String strSL = txt_soLuong.getText();
        if(strSL.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Số lượng mua không được để trống!!!");            
            return;
        }                 
        int slChuaGiao = Integer.parseInt(txt_soLuongChuaGiao.getText());
        if(slChuaGiao==0)
            return;
        int sl = Integer.parseInt(strSL);
        ChiTietDatHang ctdh = getChiTietDatHangSelect();        
        int i = 0;
        int gia = ctdh.getDonGia();
        for(Object item : dtm.getDataVector())
        {
            Vector v = (Vector)item;
            if(v.get(0).toString() == ctdh.getMaCTLH())
            {              
                sl = idxSua == -1 ? (int) v.get(4)+sl:sl;                
                if(sl>slChuaGiao)
                {
                    JOptionPane.showMessageDialog(this,"Tổng số lượng giao của tất cả các lần giao hàng của đơn đặt hàng này được lớn hơn số lượng đặt!!!");            
                    return;
                }
                v.set(4,sl);                
                v.set(3, gia); 
                v.set(5,gia*sl);
                //trường hợp sửa
                if(idxSua != -1 && idxSua != i)
                {
                    dtm.removeRow(idxSua);                    
                }
                tbl_chiTietGiaoHang.updateUI();
                btn_huyActionPerformed(null);
                return;
            }
            i ++;
        }                  
            Vector ctgh = new Vector();
            ctgh.add(ctdh.getMaCTLH());
            ctgh.add(ctdh.getChiTietLoaiHang().getHangHoa().getTenHang());
            ctgh.add(ctdh.getChiTietLoaiHang().getTenLoai());
            ctgh.add(gia);
            ctgh.add(sl);
            ctgh.add(gia*sl); 
            if(idxSua==-1)
                dtm.addRow(ctgh);                
            else
            {                
                dtm.removeRow(idxSua);
                dtm.insertRow(idxSua, ctgh);
                tbl_chiTietGiaoHang.updateUI();
                btn_huyActionPerformed(null);
            }
    }//GEN-LAST:event_btn_capNhatActionPerformed

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        btn_capNhat.setText("Thêm");
        btn_xoa.setEnabled(false);
        btn_huy.setEnabled(false);
        idxSua = -1;        
    }//GEN-LAST:event_btn_huyActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        dtm.removeRow(idxSua);
        btn_huyActionPerformed(null);
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_lamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lamMoiActionPerformed
        // TODO add your handling code here:
        dtm.setRowCount(0);
    }//GEN-LAST:event_btn_lamMoiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(dtm.getRowCount()==0)
        {
            JOptionPane.showMessageDialog(this, "Cần phải có ít nhất 1 dòng chi tiết giao hàng!!!"); 
            return ;
            
        }
        if(JOptionPane.showConfirmDialog(this, "Xác nhận tạo phiếu giao hàng? ","Thông báo",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION)
        {
            String soPhieuGiaoHang = null;
            int sl = 1;
            do
            {
                int slPGH = phieuDatHang.getPhieuGiaoHangs().size()+1;
                String soDDH =  this.phieuDatHang.getSoDonDatHang().trim();
                String sopgh = soPhieuGiaoHang = "PGH0"+soDDH+"0"+String.valueOf(slPGH+sl++);    
                if(db.getPhieuGiaoHangs().get(t->t.getSoPhieuGiao().contains(sopgh)) == null)
                {
                    soPhieuGiaoHang = sopgh;
                    break;
                }
            } while(true);              
            PhieuGiaoHang pghMoi = new PhieuGiaoHang(soPhieuGiaoHang,this.phieuDatHang.getSoDonDatHang());
            int tongSl = 0;
            int tongTien = 0;
            ArrayList<ChiTietGiaoHang> ctghs = new ArrayList<ChiTietGiaoHang>();
            for (Object item : dtm.getDataVector()) {
                Vector v = (Vector) item;
                ChiTietGiaoHang ctgh = new ChiTietGiaoHang(soPhieuGiaoHang, (String) v.get(0), (int) v.get(4));
                tongSl+=(int) v.get(4);
                tongTien += (int)v.get(5);
                ctghs.add(ctgh);
            }
            pghMoi.setTongSL(tongSl);        
            pghMoi.setThanhTien(tongTien);            
            if(db.getPhieuGiaoHangs().insert(pghMoi))
            {
                int thanhcong = db.getChiTietGiaoHangs().insert(ctghs);
                if(thanhcong == ctghs.size())                
                    JOptionPane.showMessageDialog(this, "Bạn đã tạo phiếu giao hàng thành công");                                     
                else                
                    JOptionPane.showMessageDialog(this, thanhcong + " chi tiết giao hàng đầu tiên được tạo!!!");  
                cbo_chiTietDatHangActionPerformed(null);
                dtm.setRowCount(0);
                int demSL = 0;
                for (PhieuGiaoHang pgh : phieuDatHang.getPhieuGiaoHangs())
                {
                    if(pgh.getTrangThai().equals("Bị hủy"))
                        continue;
                    demSL+=pgh.getTongSL(); 
                }
                if(phieuDatHang.getTongSL() == demSL || phieuDatHang.getPhieuGiaoHangs().stream().filter(p-> !p.getTrangThai().equals("Bị hủy")).count()==3)
                {
                    JOptionPane.showMessageDialog(this, "Đơn đặt hàng này đã đủ lượt giao hàng!");
                    this.setVisible(false);
                }    
                return;
            }
            JOptionPane.showMessageDialog(this, "Thao tác thất bại");   
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private String getMaCTLHSelect()
    {
        return Arrays.asList(cbo_chiTietDatHang.getSelectedItem().toString().split(" - ")).get(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_capNhat;
    private javax.swing.JButton btn_cong;
    private javax.swing.JButton btn_huy;
    private javax.swing.JButton btn_lamMoi;
    private javax.swing.JButton btn_tru;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_chiTietDatHang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_chiTietGiaoHang;
    private javax.swing.JTextField txt_soLuong;
    private javax.swing.JTextField txt_soLuongChuaGiao;
    private javax.swing.JTextField txt_soLuongDat;
    // End of variables declaration//GEN-END:variables
}
